import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { api } from '../api';
import { useWallet } from '@meshsdk/react';
import { Transaction } from '@meshsdk/core';

export default function Leases() {
    const { user } = useAuth();
    const { connected, wallet } = useWallet();
    const [leases, setLeases] = useState([]);
    const [loading, setLoading] = useState(true);
    const [processing, setProcessing] = useState(null);

    const load = () => {
        api.getLeases()
            .then(data => setLeases(Array.isArray(data) ? data : []))
            .catch(() => setLeases([]))
            .finally(() => setLoading(false));
    };

    useEffect(load, []);

    const handleApprove = async (lease) => {
        if (!connected) {
            alert('Please connect your Cardano wallet in the topbar to sign this contract.');
            return;
        }

        setProcessing(lease.id);
        try {
            console.log('Building on-chain transaction for lease:', lease.id);

            const tx = new Transaction({ initiator: wallet });

            // Calculate total locked amount in Lovelace (ADA * 1,000,000)
            const totalAda = Number(lease.rent_amount) + Number(lease.deposit_amount);
            const lovelace = (totalAda * 1000000).toString();

            // Destination is our Escrow Contract Address (Dummy testnet address for now)
            const escrowAddress = 'addr_test1qrz...';
            tx.sendLovelace(escrowAddress, lovelace);

            // Build, Sign and Submit via connected wallet extension
            const unsignedTx = await tx.build();
            const signedTx = await wallet.signTx(unsignedTx);
            const txHash = await wallet.submitTx(signedTx);

            console.log('Transaction confirmed on-chain. Hash:', txHash);

            await api.updateLeaseStatus(lease.id, 'active');

            // Log the escrow transaction
            await api.createEscrow({
                leaseId: lease.id,
                action: 'ContractSigned',
                amount: totalAda,
                txHash: txHash
            });

            // Auto-generate the signed lease document for both parties
            await api.createDocument({
                title: `Lease Contract CT-${lease.id.substring(0, 8).toUpperCase()}`,
                fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', // Dummy PDF representing the signed contract
                type: 'lease' // Maps to the badge style on the Documents page
            });


            load();
        } catch (err) {
            alert('Contract execution failed: ' + err.message);
        } finally {
            setProcessing(null);
        }
    };

    const updateStatus = async (id, status) => {
        try {
            await api.updateLeaseStatus(id, status);
            load();
        } catch (err) {
            alert(err.message);
        }
    };

    const statusBadge = (status) => {
        const map = {
            active: 'badge-success',
            pending: 'badge-warning',
            completed: 'badge-info',
            cancelled: 'badge-danger'
        };
        return map[status] || 'badge-info';
    };

    if (loading) return <div className="page container"><p>Loading Escrow Data...</p></div>;

    const isLandlord = user?.role?.toLowerCase() === 'landlord';

    return (
        <div className="page container fade-in">
            <div className="page-header" style={{ marginBottom: '40px', borderBottom: '1px solid var(--border)', paddingBottom: '24px' }}>
                <span className="text-overline">Contract Explorer</span>
                <h1 style={{ fontSize: '2.2rem', letterSpacing: '-0.02em', marginBottom: '8px' }}>Asset Ledger Entries</h1>
                <p>Monitor your active escrow balances and programmatic real estate leases.</p>
            </div>

            {leases.length === 0 ? (
                <div className="card empty-state" style={{ padding: '80px 20px', backgroundColor: 'var(--bg-secondary)' }}>
                    <h3 style={{ fontSize: '1.25rem', marginBottom: '8px' }}>No Active Contracts</h3>
                    <p style={{ color: 'var(--text-secondary)' }}>
                        {isLandlord
                            ? 'Initiate a lease proposal from any property in your asset portfolio.'
                            : 'Verified lease proposals will appear here once generated by a landlord.'}
                    </p>
                </div>
            ) : (
                <div className="table-wrap card" style={{ padding: 0, overflow: 'hidden', borderTop: '4px solid var(--dark-slate)' }}>
                    <table>
                        <thead>
                            <tr>
                                <th>Escrow Reference</th>
                                <th>Requirement (₳)</th>
                                <th>Locked Deposit (₳)</th>
                                <th>Contract Period</th>
                                <th>Execution Status</th>
                                <th>{isLandlord ? 'Management' : 'Signatures'}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {leases.map(l => (
                                <tr key={l.id}>
                                    <td style={{ fontWeight: 600, color: 'var(--dark-slate)' }}>CT-{l.id.toString().substring(0, 8).toUpperCase()}</td>
                                    <td style={{ fontWeight: 600, color: 'var(--accent)' }}>₳ {l.rent_amount}</td>
                                    <td>₳ {l.deposit_amount}</td>
                                    <td style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>
                                        {l.start_date} &rarr; {l.end_date}
                                    </td>
                                    <td><span className={`badge ${statusBadge(l.status)}`}>{l.status}</span></td>
                                    <td>
                                        <div style={{ display: 'flex', gap: 8 }}>
                                            {l.status === 'pending' && !isLandlord && (
                                                <button
                                                    className="btn btn-dark btn-sm btn-square"
                                                    disabled={processing === l.id}
                                                    onClick={() => handleApprove(l)}
                                                >
                                                    {processing === l.id ? 'Processing...' : 'Approve & Pay into Escrow'}
                                                </button>
                                            )}
                                            {l.status === 'pending' && isLandlord && (
                                                <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>Awaiting Tenant Signature</span>
                                            )}
                                            {l.status === 'active' && isLandlord && (
                                                <>
                                                    <button className="btn btn-secondary btn-sm btn-square" onClick={() => updateStatus(l.id, 'completed')}>
                                                        Finalize
                                                    </button>
                                                    <button className="btn btn-danger btn-sm btn-square" onClick={() => updateStatus(l.id, 'cancelled')} style={{ backgroundColor: 'transparent', color: 'var(--danger)', border: '1px solid var(--danger)' }}>
                                                        Void
                                                    </button>
                                                </>
                                            )}
                                            {l.status === 'active' && !isLandlord && (
                                                <Link to="/payments" className="btn btn-secondary btn-sm btn-square">Pay Next Installment</Link>
                                            )}
                                            {(l.status === 'completed' || l.status === 'cancelled') && (
                                                <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Contract Terminated</span>
                                            )}
                                        </div>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            )}
        </div>
    );
}
